server:
  port: 8080
  error:
    include-message: always

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        -id: persona-service
        uri: lb://persona-service
        predicates:
          -Path=/api/persona/**
        -id: imagen-service
        uri: lb://imagen-service
        predicates:
          -Path=/api/imagenMongo/**

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
