server:
  port: 8080
  error:
    include-message: always

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: localhost

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: persona-service        
          predicates:
          - Path=/api/persona/**
          uri: lb://persona-service #http://localhost8080

        - id: imagen-service        
          predicates:
          - Path=/api/imagenMongo/**
          uri: lb://imagen-service #http://localhost8080
        

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
