server:
  port: 8080
  error:
    include-message: always

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: persona-service
        uri: http://localhost8080 #lb://persona-service
        predicates:
          - Path=/api/persona/**
        - id: imagen-service
        uri: lb://imagen-service
        predicates:
          - Path=/api/imagenMongo/**

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
