server:
  port: 8080
  error:
    include-message: always

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        -id: persona-service
        uri: lb://persona-service
        predicates:
          -Path=/api/persona/**
        -id: imagen-service
        uri: lb://imagen-service
        predicates:
          -Path=/api/imagenMongo/**

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
