server:
  port: ${PORT:${SERVER_PORT:0}}
  error:
    include-message: always
################### Mongo Configuration ##########################
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/db_practica
      database: db_practica
      auto-index-creation: true

################### Img Configuration ##########################
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 500MB
      max-request-size: 500MB

  main:
    allow-circular-references: true

  mvc:
    pathmatch:
      matching-strategy : ANT_PATH_MATCHER

  application:
    name: imagen-service
    zipkin: http://localhost:9411

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    path: /index.html


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

error: 
  whitelabel:
    enabled: false

#actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"