server:
  port: ${PORT:${SERVER_PORT:0}}
  error:
    include-message: always
################### Mongo Configuration ##########################
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/db_practica
      database: db_practica
      auto-index-creation: true

################### Img Configuration ##########################
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 500MB
      max-request-size: 500MB

  main:
    allow-circular-references: true

  mvc:
    pathmatch:
      matching-strategy : ANT_PATH_MATCHER

  application:
    name: imagen-service

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}