server:
  port: ${PORT:${SERVER_PORT:0}}
  error:
    include-message: always
################### Mysql Configuration ##########################
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_practica
    username: root
    password:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect : org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true

  main:
    allow-circular-references: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  application:
    name: persona-service

#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

# resilience4j.circuitbreaker:
#     instances:
#         imagenCB:
#             registerHealthIndicator: true
#             slidingWindowSize: 10
#             permittedNumberOfCallsInHalfOpenState: 3
#             slidingWindowType: TIME_BASED
#             minimumNumberOfCalls: 4
#             waitDurationInOpenState: 5s
#             failureRateThreshold: 50
#             eventConsumerBufferSize: 10
#         allCB:
#             registerHealthIndicator: true
#             slidingWindowSize: 10
#             permittedNumberOfCallsInHalfOpenState: 3
#             slidingWindowType: TIME_BASED
#             minimumNumberOfCalls: 4
#             waitDurationInOpenState: 5s
#             failureRateThreshold: 50
#             eventConsumerBufferSize: 10
            

# #hystrix con feign
# Feign:
#   hystrix:
#     enabled: true
# #actuator
# management:
#   endpoints:
#     web:
#       exposure:
#         include: "*"